Documentation:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Rakefile'
    - config.ru
  Exclude:
    - db/schema.rb
    - 'db/fixtures/**/*'
    - 'config/**/*'
  DisplayCopNames: true
LineLength:
  Max: 100
